import React, { useState } from 'react';
import { Form, Button, Spinner, Alert, Card, Accordion } from 'react-bootstrap';
import { 
    FaMagic, FaCopy, FaDownload, FaSyncAlt, FaRegLightbulb, 
    FaFilter, FaEye, FaUsers, FaShoppingCart, FaHeart, FaChevronDown 
} from 'react-icons/fa';
import toast from 'react-hot-toast';
import './MarketingFunnelBuilder.css';
import aiService from '../../../../services/aiService.js';

const MarketingFunnelBuilder = () => {
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [funnel, setFunnel] = useState(null);
    
    const [formData, setFormData] = useState({
        productName: '',
        businessType: 'SaaS',
        targetAudience: '',
        mainGoal: 'Sales'
    });

    const businessTypes = [
        'SaaS', 'E-commerce', 'Agency / Service', 'B2B Software', 
        'Coaching / Info Product', 'Local Business', 'Mobile App'
    ];

    const goals = [
        'Sales', 'Lead Generation', 'App Downloads', 
        'Event Attendance', 'Brand Awareness'
    ];

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const callGeminiAI = async (prompt) => {
                
        const response = await axios.post(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
            contents: [{ parts: [{ text: prompt }] }]
        });

        const data = response.data;
        if (data.error) throw new Error(data.error.message);
        return data.candidates[0].content.parts[0].text;
    };

    const generateFunnel = async () => {
        if (!formData.productName || !formData.targetAudience) {
            toast.error('Please enter product name and target audience.');
            return;
        }

        setLoading(true);
        setError('');
        
        const prompt = `Design a complete 4-stage marketing funnel for:
        Product Name: "${formData.productName}"
        Business Type: ${formData.businessType}
        Target Audience: "${formData.targetAudience}"
        Main Goal: ${formData.mainGoal}
        
        Please provide the funnel in the following JSON format:
        {
            "awareness": {
                "title": "Awareness (Top of Funnel)",
                "strategy": "How to get discovered",
                "tactics": ["Tactic 1", "Tactic 2"],
                "contentIdeas": ["Idea 1", "Idea 2"]
            },
            "interest": {
                "title": "Interest & Consideration (Middle of Funnel)",
                "strategy": "How to educate and build trust",
                "tactics": ["Tactic 1", "Tactic 2"],
                "contentIdeas": ["Idea 1", "Idea 2"]
            },
            "conversion": {
                "title": "Conversion (Bottom of Funnel)",
                "strategy": "How to close the deal",
                "tactics": ["Tactic 1", "Tactic 2"],
                "contentIdeas": ["Idea 1", "Idea 2"]
            },
            "retention": {
                "title": "Retention & Advocacy (Post-Purchase)",
                "strategy": "How to keep them coming back",
                "tactics": ["Tactic 1", "Tactic 2"],
                "contentIdeas": ["Idea 1", "Idea 2"]
            }
        }
        Provide only the JSON object.`;

        try {
            const responseText = await callGeminiAI(prompt);
            const jsonStart = responseText.indexOf('{');
            const jsonEnd = responseText.lastIndexOf('}') + 1;
            const jsonStr = responseText.substring(jsonStart, jsonEnd);
            const data = JSON.parse(jsonStr);
            
            setFunnel(data);
            toast.success('Marketing funnel mapped out!');
        } catch (err) {
            setError('Failed to build funnel: ' + err.message);
            toast.error('Build failed.');
        } finally {
            setLoading(false);
        }
    };

    const copyFunnel = () => {
        const text = JSON.stringify(funnel, null, 2);
        navigator.clipboard.writeText(text);
        toast.success('Funnel JSON copied!');
    };

    const downloadFunnel = () => {
        const content = `
MARKETING FUNNEL: ${formData.productName}
Generated by WebzenTools

1. AWARENESS (TOFU)
Strategy: ${funnel.awareness.strategy}
Tactics: ${funnel.awareness.tactics.join(', ')}
Content: ${funnel.awareness.contentIdeas.join(', ')}

2. INTEREST (MOFU)
Strategy: ${funnel.interest.strategy}
Tactics: ${funnel.interest.tactics.join(', ')}
Content: ${funnel.interest.contentIdeas.join(', ')}

3. CONVERSION (BOFU)
Strategy: ${funnel.conversion.strategy}
Tactics: ${funnel.conversion.tactics.join(', ')}
Content: ${funnel.conversion.contentIdeas.join(', ')}

4. RETENTION
Strategy: ${funnel.retention.strategy}
Tactics: ${funnel.retention.tactics.join(', ')}
Content: ${funnel.retention.contentIdeas.join(', ')}
        `.trim();

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${formData.productName.replace(/\s+/g, '_')}_funnel.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const resetTool = () => {
        setFunnel(null);
        setFormData({
            productName: '',
            businessType: 'SaaS',
            targetAudience: '',
            mainGoal: 'Sales'
        });
        setError('');
    };

    return (
        <div className="funnel-builder-container py-4">
            <div className="text-center mb-5">
                <div className="premium-badge mb-3">
                    <FaFilter className="me-2" /> Strategic Journey Planner
                </div>
                <h1 className="display-5 fw-bold mb-3 gradient-text">Marketing Funnel Builder</h1>
                <p className="text-muted mx-auto" style={{ maxWidth: '600px' }}>
                    Map out your entire customer journey. From the first click to the final purchase and beyond, build a funnel that scales your business.
                </p>
            </div>

            {error && <Alert variant="danger" className="mb-4 rounded-4 border-0 shadow-sm">{error}</Alert>}

            <div className="row g-4">
                {/* Input Section */}
                <div className={funnel ? "col-lg-5" : "col-lg-8 mx-auto"}>
                    <Card className="premium-card border-0 shadow-lg h-100">
                        <Card.Body className="p-4 p-md-5">
                            <div className="d-flex align-items-center gap-3 mb-4">
                                <div className="p-3 rounded-4 bg-primary bg-opacity-10 text-primary">
                                    <FaUsers size={24} />
                                </div>
                                <div>
                                    <h2 className="h4 fw-bold mb-1">Funnel Inputs</h2>
                                    <p className="text-muted mb-0 small">Define your roadmap</p>
                                </div>
                            </div>

                            <Form>
                                <Form.Group className="mb-4">
                                    <Form.Label className="fw-bold text-dark small text-uppercase">Product / Service Name</Form.Label>
                                    <Form.Control 
                                        name="productName"
                                        placeholder="e.g. Zen CRM"
                                        value={formData.productName}
                                        onChange={handleInputChange}
                                        className="premium-input"
                                    />
                                </Form.Group>

                                <Form.Group className="mb-4">
                                    <Form.Label className="fw-bold text-dark small text-uppercase">Target Audience</Form.Label>
                                    <Form.Control 
                                        name="targetAudience"
                                        placeholder="e.g. Small business owners looking to automate sales"
                                        value={formData.targetAudience}
                                        onChange={handleInputChange}
                                        className="premium-input"
                                    />
                                </Form.Group>

                                <div className="row">
                                    <div className="col-md-6 mb-4">
                                        <Form.Label className="fw-bold text-dark small text-uppercase">Business Type</Form.Label>
                                        <Form.Select 
                                            name="businessType"
                                            value={formData.businessType}
                                            onChange={handleInputChange}
                                            className="premium-input"
                                        >
                                            {businessTypes.map(type => (
                                                <option key={type} value={type}>{type}</option>
                                            ))}
                                        </Form.Select>
                                    </div>
                                    <div className="col-md-6 mb-4">
                                        <Form.Label className="fw-bold text-dark small text-uppercase">Primary Goal</Form.Label>
                                        <Form.Select 
                                            name="mainGoal"
                                            value={formData.mainGoal}
                                            onChange={handleInputChange}
                                            className="premium-input"
                                        >
                                            {goals.map(goal => (
                                                <option key={goal} value={goal}>{goal}</option>
                                            ))}
                                        </Form.Select>
                                    </div>
                                </div>

                                <Button 
                                    className="btn-premium w-100 py-3 d-flex align-items-center justify-content-center gap-2 mt-4"
                                    onClick={generateFunnel}
                                    disabled={loading}
                                >
                                    {loading ? <Spinner animation="border" size="sm" /> : <FaMagic />}
                                    {loading ? 'Building Customer Journey...' : 'Map Full Marketing Funnel'}
                                </Button>
                            </Form>
                        </Card.Body>
                    </Card>
                </div>

                {/* Results Section */}
                {funnel && (
                    <div className="col-lg-7">
                        <Card className="premium-card border-0 shadow-lg h-100 overflow-hidden">
                            <Card.Body className="p-4 p-md-5">
                                <div className="d-flex justify-content-between align-items-center mb-4">
                                    <div className="d-flex align-items-center gap-3">
                                        <div className="p-3 rounded-4 bg-success bg-opacity-10 text-success">
                                            <FaFilter size={24} />
                                        </div>
                                        <div>
                                            <h2 className="h4 fw-bold mb-1">Your Growth Funnel</h2>
                                            <p className="text-muted mb-0 small">End-to-end strategy</p>
                                        </div>
                                    </div>
                                    <div className="d-flex gap-2">
                                        <button className="btn btn-light rounded-pill p-2" onClick={downloadFunnel} title="Download .txt">
                                            <FaDownload />
                                        </button>
                                        <button className="btn btn-light rounded-pill p-2" onClick={resetTool} title="Reset">
                                            <FaSyncAlt />
                                        </button>
                                    </div>
                                </div>

                                <Accordion defaultActiveKey="0" className="premium-accordion">
                                    {/* Awareness */}
                                    <Accordion.Item eventKey="0" className="border-0 mb-3 rounded-4 overflow-hidden shadow-sm">
                                        <Accordion.Header className="awareness-header">
                                            <div className="d-flex align-items-center gap-3">
                                                <div className="p-2 rounded-circle bg-primary text-white"><FaEye size={12} /></div>
                                                <span className="fw-bold">Awareness (TOFU)</span>
                                            </div>
                                        </Accordion.Header>
                                        <Accordion.Body className="bg-white">
                                            <div className="fw-bold text-primary mb-2 small text-uppercase">Strategy</div>
                                            <p className="small mb-3">{funnel.awareness.strategy}</p>
                                            <div className="row g-3">
                                                <div className="col-6">
                                                    <div className="fw-bold extra-small text-muted mb-1 uppercase">Tactics</div>
                                                    <ul className="extra-small ps-3 mb-0">
                                                        {funnel.awareness.tactics.map((t, i) => <li key={i}>{t}</li>)}
                                                    </ul>
                                                </div>
                                                <div className="col-6">
                                                    <div className="fw-bold extra-small text-muted mb-1 uppercase">Content</div>
                                                    <ul className="extra-small ps-3 mb-0">
                                                        {funnel.awareness.contentIdeas.map((c, i) => <li key={i}>{c}</li>)}
                                                    </ul>
                                                </div>
                                            </div>
                                        </Accordion.Body>
                                    </Accordion.Item>

                                    {/* Interest */}
                                    <Accordion.Item eventKey="1" className="border-0 mb-3 rounded-4 overflow-hidden shadow-sm">
                                        <Accordion.Header className="interest-header">
                                            <div className="d-flex align-items-center gap-3">
                                                <div className="p-2 rounded-circle bg-info text-white"><FaUsers size={12} /></div>
                                                <span className="fw-bold">Interest (MOFU)</span>
                                            </div>
                                        </Accordion.Header>
                                        <Accordion.Body className="bg-white">
                                            <div className="fw-bold text-info mb-2 small text-uppercase">Strategy</div>
                                            <p className="small mb-3">{funnel.interest.strategy}</p>
                                            <div className="row g-3">
                                                <div className="col-6">
                                                    <div className="fw-bold extra-small text-muted mb-1 uppercase">Tactics</div>
                                                    <ul className="extra-small ps-3 mb-0">
                                                        {funnel.interest.tactics.map((t, i) => <li key={i}>{t}</li>)}
                                                    </ul>
                                                </div>
                                                <div className="col-6">
                                                    <div className="fw-bold extra-small text-muted mb-1 uppercase">Content</div>
                                                    <ul className="extra-small ps-3 mb-0">
                                                        {funnel.interest.contentIdeas.map((c, i) => <li key={i}>{c}</li>)}
                                                    </ul>
                                                </div>
                                            </div>
                                        </Accordion.Body>
                                    </Accordion.Item>

                                    {/* Conversion */}
                                    <Accordion.Item eventKey="2" className="border-0 mb-3 rounded-4 overflow-hidden shadow-sm">
                                        <Accordion.Header className="conversion-header">
                                            <div className="d-flex align-items-center gap-3">
                                                <div className="p-2 rounded-circle bg-success text-white"><FaShoppingCart size={12} /></div>
                                                <span className="fw-bold">Conversion (BOFU)</span>
                                            </div>
                                        </Accordion.Header>
                                        <Accordion.Body className="bg-white">
                                            <div className="fw-bold text-success mb-2 small text-uppercase">Strategy</div>
                                            <p className="small mb-3">{funnel.conversion.strategy}</p>
                                            <div className="row g-3">
                                                <div className="col-6">
                                                    <div className="fw-bold extra-small text-muted mb-1 uppercase">Tactics</div>
                                                    <ul className="extra-small ps-3 mb-0">
                                                        {funnel.conversion.tactics.map((t, i) => <li key={i}>{t}</li>)}
                                                    </ul>
                                                </div>
                                                <div className="col-6">
                                                    <div className="fw-bold extra-small text-muted mb-1 uppercase">Content</div>
                                                    <ul className="extra-small ps-3 mb-0">
                                                        {funnel.conversion.contentIdeas.map((c, i) => <li key={i}>{c}</li>)}
                                                    </ul>
                                                </div>
                                            </div>
                                        </Accordion.Body>
                                    </Accordion.Item>

                                    {/* Retention */}
                                    <Accordion.Item eventKey="3" className="border-0 mb-0 rounded-4 overflow-hidden shadow-sm">
                                        <Accordion.Header className="retention-header">
                                            <div className="d-flex align-items-center gap-3">
                                                <div className="p-2 rounded-circle bg-danger text-white"><FaHeart size={12} /></div>
                                                <span className="fw-bold">Retention (Advocacy)</span>
                                            </div>
                                        </Accordion.Header>
                                        <Accordion.Body className="bg-white">
                                            <div className="fw-bold text-danger mb-2 small text-uppercase">Strategy</div>
                                            <p className="small mb-3">{funnel.retention.strategy}</p>
                                            <div className="row g-3">
                                                <div className="col-6">
                                                    <div className="fw-bold extra-small text-muted mb-1 uppercase">Tactics</div>
                                                    <ul className="extra-small ps-3 mb-0">
                                                        {funnel.retention.tactics.map((t, i) => <li key={i}>{t}</li>)}
                                                    </ul>
                                                </div>
                                                <div className="col-6">
                                                    <div className="fw-bold extra-small text-muted mb-1 uppercase">Content</div>
                                                    <ul className="extra-small ps-3 mb-0">
                                                        {funnel.retention.contentIdeas.map((c, i) => <li key={i}>{c}</li>)}
                                                    </ul>
                                                </div>
                                            </div>
                                        </Accordion.Body>
                                    </Accordion.Item>
                                </Accordion>
                            </Card.Body>
                        </Card>
                    </div>
                )}
            </div>

            {/* Footer Tips */}
            {!loading && !funnel && (
                <div className="mt-5 p-4 glass-panel rounded-4 border border-white">
                    <h5 className="h6 fw-bold text-dark d-flex align-items-center gap-2 mb-3">
                        <FaRegLightbulb className="text-warning" /> Funnel Optimization Secrets
                    </h5>
                    <div className="row g-4">
                        <div className="col-md-4">
                            <div className="tip-card p-3 rounded-3 bg-white shadow-sm h-100 border-start border-4 border-primary">
                                <div className="fw-bold small mb-1 text-primary">TOFU: Cast a Wide Net</div>
                                <p className="extra-small text-muted mb-0">Awareness stage is about teaching, not selling. Use educational blogs, social posts, and videos.</p>
                            </div>
                        </div>
                        <div className="col-md-4">
                            <div className="tip-card p-3 rounded-3 bg-white shadow-sm h-100 border-start border-4 border-info">
                                <div className="fw-bold small mb-1 text-info">MOFU: Build Authority</div>
                                <p className="extra-small text-muted mb-0">Interest stage is where you prove you're the expert. Use webinars, case studies, and comparison guides.</p>
                            </div>
                        </div>
                        <div className="col-md-4">
                            <div className="tip-card p-3 rounded-3 bg-white shadow-sm h-100 border-start border-4 border-success">
                                <div className="fw-bold small mb-1 text-success">BOFU: Remove Friction</div>
                                <p className="extra-small text-muted mb-0">Conversion stage needs to be easy. Use free trials, discounts, and clear product demos.</p>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default MarketingFunnelBuilder;
