import React, { useState, useRef, useEffect } from "react";
import { toast } from "react-hot-toast";
import { FaDownload, FaUpload, FaTrash, FaCheck, FaExternalLinkAlt, FaLayerGroup, FaShieldAlt } from "react-icons/fa";
import JSZip from "jszip";
import "./FaviconGenerator.css";

const FaviconGenerator = () => {
  const [originalImage, setOriginalImage] = useState(null);
  const [previews, setPreviews] = useState({});
  const [generating, setGenerating] = useState(false);
  const fileInputRef = useRef(null);

  const sizes = [
    { size: 16, label: "16x16 (Favicon)" },
    { size: 32, label: "32x32 (Standard)" },
    { size: 48, label: "48x48 (Desktop)" },
    { size: 64, label: "64x64 (Hi-DPI)" },
    { size: 128, label: "128x128 (Web App)" },
    { size: 180, label: "180x180 (Apple)" },
    { size: 192, label: "192x192 (Android)" },
    { size: 512, label: "512x512 (Splash)" },
  ];

  const handleImageUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        const img = new Image();
        img.onload = () => {
          setOriginalImage(img);
          generatePreviews(img);
          toast.success("Image uploaded!");
        };
        img.src = event.target.result;
      };
      reader.readAsDataURL(file);
    }
  };

  const generatePreviews = (img) => {
    const newPreviews = {};
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");

    sizes.forEach(({ size }) => {
      canvas.width = size;
      canvas.height = size;
      ctx.clearRect(0, 0, size, size);
      
      // Maintain aspect ratio and center
      const scale = Math.min(size / img.width, size / img.height);
      const x = (size / 2) - (img.width / 2) * scale;
      const y = (size / 2) - (img.height / 2) * scale;
      
      ctx.drawImage(img, x, y, img.width * scale, img.height * scale);
      newPreviews[size] = canvas.toDataURL("image/png");
    });

    setPreviews(newPreviews);
  };

  const handleDownloadAll = async () => {
    if (!originalImage) return;
    setGenerating(true);
    try {
      const zip = new JSZip();
      const folder = zip.folder("favicons");

      for (const { size } of sizes) {
        const dataUrl = previews[size];
        const base64Data = dataUrl.split(",")[1];
        folder.file(`favicon-${size}x${size}.png`, base64Data, { base64: true });
      }

      // Add a basic instructions file
      folder.file("README.txt", "Favicon package generated by WebzenTools.\n\nUsage:\nInclude the <link> tags in your HTML <head> section.");

      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const link = document.createElement("a");
      link.href = url;
      link.download = "webzentools-favicons.zip";
      link.click();
      URL.revokeObjectURL(url);
      toast.success("Favicon package downloaded!");
    } catch (error) {
      toast.error("Failed to generate ZIP file");
      console.error(error);
    } finally {
      setGenerating(false);
    }
  };

  const resetTool = () => {
    setOriginalImage(null);
    setPreviews({});
    if (fileInputRef.current) fileInputRef.current.value = "";
    toast.success("Tool reset!");
  };

  return (
    <div className="favicon-generator-container">
      <div className="row g-4">
        {/* Left Side: Preview & Upload */}
        <div className="col-lg-7">
          <div className="premium-card p-4 h-100">
            <h5 className="fw-bold mb-4 text-dark">Live Tab Preview</h5>
            
            {/* Browser Tab Simulation */}
            <div className="tab-simulation-wrapper mb-5">
              <div className="tab-simulation">
                <div className="browser-tab active">
                  <img 
                    src={previews[16] || "https://webzentools.com/favicon.ico"} 
                    alt="Favicon" 
                    className="tab-icon" 
                  />
                  <span>WebzenTools - My Awesome Site</span>
                  <span className="tab-close ms-2">×</span>
                </div>
                <div className="browser-tab" style={{ background: 'rgba(255,255,255,0.05)', color: 'rgba(255,255,255,0.5)', borderBottom: 'none' }}>
                  <span>New Tab</span>
                </div>
              </div>
              <div className="browser-address-bar">
                <FaShieldAlt className="text-success me-2" size={12} />
                <span>https://yourwebsite.com</span>
              </div>
            </div>

            {!originalImage ? (
              <div 
                className="upload-area d-flex flex-column align-items-center justify-content-center"
                onClick={() => fileInputRef.current.click()}
              >
                <div className="upload-icon-wrapper mb-3">
                  <FaUpload size={40} className="text-primary" />
                </div>
                <h5 className="fw-bold text-dark">Upload Your Logo</h5>
                <p className="text-muted small">Supports PNG, JPG, WEBP, or SVG</p>
                <input 
                  type="file" 
                  ref={fileInputRef} 
                  onChange={handleImageUpload} 
                  accept="image/*" 
                  className="d-none" 
                />
              </div>
            ) : (
              <div className="size-grid">
                {sizes.map(({ size, label }) => (
                  <div key={size} className="size-item">
                    <div className="preview-box" style={{ width: 64, height: 64 }}>
                      <img 
                        src={previews[size]} 
                        alt={label} 
                        style={{ 
                          width: Math.min(size, 48), 
                          height: Math.min(size, 48),
                          objectFit: 'contain'
                        }} 
                      />
                    </div>
                    <span className="size-label">{size}x{size}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Right Side: Actions & Info */}
        <div className="col-lg-5">
          <div className="premium-card p-4 h-100 glass-card">
            <h4 className="fw-bold mb-4 text-dark">Favicon Package</h4>
            <p className="text-muted small mb-4">
              Generate a complete set of favicons for all platforms (Windows, iOS, Android, and Web). Our tool creates perfectly sized icons and packages them into a single ZIP.
            </p>

            <div className="d-grid gap-3 mb-4">
              <button 
                className="btn btn-generate action-btn"
                onClick={handleDownloadAll}
                disabled={!originalImage || generating}
              >
                {generating ? "Generating..." : (
                  <>
                    <FaDownload className="me-2" /> Download All Icons (.ZIP)
                  </>
                )}
              </button>
              <button 
                className="btn btn-reset action-btn"
                onClick={resetTool}
                disabled={!originalImage}
                style={{ background: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.2)', color: '#ef4444' }}
              >
                <FaTrash className="me-2" /> Start Over
              </button>
            </div>

            <div className="usage-info mt-4 p-3 rounded-4" style={{ background: 'rgba(56, 189, 248, 0.05)', border: '1px solid rgba(56, 189, 248, 0.1)' }}>
              <h6 className="fw-bold text-primary mb-2 d-flex align-items-center">
                <FaExternalLinkAlt className="me-2" size={12} /> Pro Tip
              </h6>
              <p className="text-muted small mb-0">
                For the best results, use a high-resolution square image (at least 512x512px) with a transparent background.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* About Section */}
      <div className="mt-5 pt-5 border-top border-secondary border-opacity-10">
        <h2 className="fw-bold mb-4 text-dark">About Favicon Generator</h2>
        <p className="text-muted" style={{ lineHeight: "1.8" }}>
          The Favicon Generator is an essential tool for web developers and designers. It streamlines the process of creating multi-platform favicons, ensuring your website looks professional on every device. By generating a full set of sizes, we help you maintain brand consistency across browser tabs, taskbars, and home screens.
        </p>

        <div className="row g-4 mt-4">
          <div className="col-md-4">
            <div className="feature-item">
              <div className="icon-wrapper mb-3 text-primary">
                <FaLayerGroup size={24} />
              </div>
              <h5 className="fw-bold text-dark">Multi-Size Support</h5>
              <p className="text-muted small mb-0">Automatic generation of 8+ standard sizes from 16px to 512px in a single click.</p>
            </div>
          </div>
          <div className="col-md-4">
            <div className="feature-item">
              <div className="icon-wrapper mb-3 text-success">
                <FaDownload size={24} />
              </div>
              <h5 className="fw-bold text-dark">Batch ZIP Export</h5>
              <p className="text-muted small mb-0">Download your entire favicon set as a structured ZIP file ready for deployment.</p>
            </div>
          </div>
          <div className="col-md-4">
            <div className="feature-item">
              <div className="icon-wrapper mb-3 text-info">
                <FaShieldAlt size={24} />
              </div>
              <h5 className="fw-bold text-dark">Privacy Guaranteed</h5>
              <p className="text-muted small mb-0">Images are processed locally. We never store or upload your source files to our servers.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FaviconGenerator;
