import React, { useState, useEffect } from 'react';
import { Row, Col, Form, Button, Alert } from 'react-bootstrap';
import { FaRobot, FaPlus, FaTrash, FaCopy, FaDownload, FaInfoCircle, FaCheck, FaTimes } from 'react-icons/fa';
import './RobotsTxtGenerator.css';

const RobotsTxtGenerator = () => {
    const [globalAllow, setGlobalAllow] = useState('allow');
    const [crawlDelay, setCrawlDelay] = useState('');
    const [sitemapUrl, setSitemapUrl] = useState('');
    const [rules, setRules] = useState([
        { agent: '*', type: 'disallow', path: '/admin/' },
        { agent: '*', type: 'disallow', path: '/temp/' }
    ]);
    const [generatedCode, setGeneratedCode] = useState('');
    const [copied, setCopied] = useState(false);

    const addRule = () => {
        setRules([...rules, { agent: '*', type: 'disallow', path: '' }]);
    };

    const removeRule = (index) => {
        setRules(rules.filter((_, i) => i !== index));
    };

    const updateRule = (index, field, value) => {
        const newRules = [...rules];
        newRules[index][field] = value;
        setRules(newRules);
    };

    useEffect(() => {
        let code = `# Robots.txt generated by WebzenTools\n\n`;
        
        code += `User-agent: *\n`;
        if (globalAllow === 'disallow') {
            code += `Disallow: /\n`;
        } else {
            code += `Allow: /\n`;
        }

        if (crawlDelay) {
            code += `Crawl-delay: ${crawlDelay}\n`;
        }

        // Group rules by agent
        const agentRules = {};
        rules.forEach(rule => {
            if (!rule.path) return;
            if (!agentRules[rule.agent]) agentRules[rule.agent] = [];
            agentRules[rule.agent].push(rule);
        });

        Object.entries(agentRules).forEach(([agent, rList]) => {
            if (agent !== '*') code += `\nUser-agent: ${agent}\n`;
            rList.forEach(r => {
                const prefix = r.type === 'disallow' ? 'Disallow' : 'Allow';
                code += `${prefix}: ${r.path}\n`;
            });
        });

        if (sitemapUrl) {
            code += `\nSitemap: ${sitemapUrl}\n`;
        }

        setGeneratedCode(code);
    }, [globalAllow, crawlDelay, sitemapUrl, rules]);

    const handleCopy = () => {
        navigator.clipboard.writeText(generatedCode);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const element = document.createElement("a");
        const file = new Blob([generatedCode], {type: 'text/plain'});
        element.href = URL.createObjectURL(file);
        element.download = "robots.txt";
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    };

    const renderPreview = () => {
        return generatedCode.split('\n').map((line, i) => {
            if (line.startsWith('#')) return <div key={i} className="comment-syntax">{line}</div>;
            const [kw, ...rest] = line.split(':');
            if (rest.length === 0) return <div key={i}>{line}</div>;
            return (
                <div key={i}>
                    <span className="kw-syntax">{kw}:</span>
                    <span className="val-syntax">{rest.join(':')}</span>
                </div>
            );
        });
    };

    return (
        <div className="robots-txt-generator">
            <Row className="gy-4">
                <Col lg={7}>
                    <div className="p-4 glass-card rounded-4 mb-4">
                        <div className="section-header">
                            <FaRobot size={20} />
                            <h5 className="fw-bold mb-0">Global Settings</h5>
                        </div>
                        <Row className="gy-3">
                            <Col md={6}>
                                <Form.Label className="small fw-bold">Default Crawl Behavior</Form.Label>
                                <div className="d-flex gap-2">
                                    <Button 
                                        variant={globalAllow === 'allow' ? "primary" : "outline-secondary"}
                                        className="flex-grow-1 rounded-3 d-flex align-items-center justify-content-center"
                                        onClick={() => setGlobalAllow('allow')}
                                    >
                                        <FaCheck className="me-2" /> Allow All
                                    </Button>
                                    <Button 
                                        variant={globalAllow === 'disallow' ? "danger" : "outline-secondary"}
                                        className="flex-grow-1 rounded-3 d-flex align-items-center justify-content-center"
                                        onClick={() => setGlobalAllow('disallow')}
                                    >
                                        <FaTimes className="me-2" /> Disallow All
                                    </Button>
                                </div>
                            </Col>
                            <Col md={6}>
                                <Form.Group>
                                    <Form.Label className="small fw-bold">Crawl-Delay (Seconds)</Form.Label>
                                    <Form.Control 
                                        type="number" 
                                        placeholder="e.g. 5" 
                                        value={crawlDelay}
                                        onChange={(e) => setCrawlDelay(e.target.value)}
                                        className="rounded-3"
                                    />
                                </Form.Group>
                            </Col>
                            <Col md={12}>
                                <Form.Group>
                                    <Form.Label className="small fw-bold">Sitemap URL</Form.Label>
                                    <Form.Control 
                                        type="text" 
                                        placeholder="https://example.com/sitemap.xml" 
                                        value={sitemapUrl}
                                        onChange={(e) => setSitemapUrl(e.target.value)}
                                        className="rounded-3"
                                    />
                                </Form.Group>
                            </Col>
                        </Row>
                    </div>

                    <div className="p-4 glass-card rounded-4">
                        <div className="section-header">
                            <FaInfoCircle size={20} />
                            <h5 className="fw-bold mb-0">Custom Directives</h5>
                        </div>
                        
                        <div className="rules-list">
                            {rules.map((rule, idx) => (
                                <div key={idx} className="rule-item">
                                    <button className="btn btn-link btn-remove-rule" onClick={() => removeRule(idx)}>
                                        <FaTrash size={14} />
                                    </button>
                                    <Row className="g-2">
                                        <Col md={4}>
                                            <Form.Control 
                                                size="sm"
                                                placeholder="User-agent (*)"
                                                value={rule.agent}
                                                onChange={(e) => updateRule(idx, 'agent', e.target.value)}
                                                className="border-0 bg-white"
                                            />
                                        </Col>
                                        <Col md={3}>
                                            <Form.Select 
                                                size="sm"
                                                value={rule.type}
                                                onChange={(e) => updateRule(idx, 'type', e.target.value)}
                                                className="border-0 bg-white"
                                            >
                                                <option value="disallow">Disallow</option>
                                                <option value="allow">Allow</option>
                                            </Form.Select>
                                        </Col>
                                        <Col md={5}>
                                            <Form.Control 
                                                size="sm"
                                                placeholder="/path/to/block"
                                                value={rule.path}
                                                onChange={(e) => updateRule(idx, 'path', e.target.value)}
                                                className="border-0 bg-white"
                                            />
                                        </Col>
                                    </Row>
                                </div>
                            ))}
                        </div>

                        <button className="btn btn-add-rule mt-2" onClick={addRule}>
                            <FaPlus className="me-2" /> Add New Directive
                        </button>
                    </div>
                </Col>

                <Col lg={5}>
                    <div className="code-preview-container">
                        <div className="code-preview">
                            {renderPreview()}
                        </div>
                        
                        <div className="preview-actions">
                            <Button 
                                variant={copied ? "success" : "primary"} 
                                className="btn-action"
                                onClick={handleCopy}
                            >
                                {copied ? <><FaCheck className="me-2" /> Copied!</> : <><FaCopy className="me-2" /> Copy Code</>}
                            </Button>
                            <Button 
                                variant="dark" 
                                className="btn-action"
                                onClick={handleDownload}
                            >
                                <FaDownload className="me-2" /> Download
                            </Button>
                        </div>

                        <Alert variant="warning" className="mt-4 border-0 shadow-sm rounded-4">
                            <div className="d-flex align-items-start">
                                <FaInfoCircle className="mt-1 me-3 flex-shrink-0" />
                                <div className="small">
                                    <strong>SEO Advice:</strong> Don't block your CSS, JS, or images, as search engines need these to fully understand your page layout.
                                </div>
                            </div>
                        </Alert>
                    </div>
                </Col>
            </Row>

            <div className="mt-5 pt-4 border-top">
                <h3 className="h5 fw-bold mb-3">What is a Robots.txt File?</h3>
                <p className="text-muted small">
                    The <code>robots.txt</code> file is a simple text file placed in your website's root directory that tells search engine crawlers which pages or sections of your site they should or should not crawl. While it's not a way to "hide" content from the public, it is essential for managing your site's crawl budget and preventing search engines from indexing sensitive areas like admin panels.
                </p>
                <Row className="gy-3 mt-2">
                    <Col md={4}>
                        <div className="p-3 bg-light rounded-4 h-100">
                            <h6 className="fw-bold mb-2">User-agent</h6>
                            <p className="text-muted small mb-0">Specifies which crawler the rule applies to (e.g., Googlebot, Bingbot, or * for all).</p>
                        </div>
                    </Col>
                    <Col md={4}>
                        <div className="p-3 bg-light rounded-4 h-100">
                            <h6 className="fw-bold mb-2">Disallow</h6>
                            <p className="text-muted small mb-0">Tells the crawler not to visit a specific URL path or directory.</p>
                        </div>
                    </Col>
                    <Col md={4}>
                        <div className="p-3 bg-light rounded-4 h-100">
                            <h6 className="fw-bold mb-2">Sitemap</h6>
                            <p className="text-muted small mb-0">Helps crawlers find your XML sitemap for better indexing efficiency.</p>
                        </div>
                    </Col>
                </Row>
            </div>
        </div>
    );
};

export default RobotsTxtGenerator;
